config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :users
  end
  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    @recruiters = User.where(title: "Recruiter")
    @managers = User.where(title: "Hiring Manager")
    @seekers = User.where(title: "Job Seeker")
    @current = User.last
    render json: {"recruiters" => @recruiters, "managers" => @managers, "seekers" => @seekers, "current_user" => @current }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :title, :positions, :experience, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="site">
<head>
  <title>Kon Tiki Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :positions %><br>
    <%= f.text_area :positions %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.number_field :experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div ng-controller="mainController as main" ng-init="index()" class="container">

<!-- Navbar Tabs -->
<nav-tabs></nav-tabs>

<div class="panel" ng-show="isSelected(1)">

<!-- Filter Results by Search -->
<search-form></search-form>

  <h3 class="section-titles">Recruiters</h3>
  <ul ng-hide="profileShow()">
    <li ng-repeat="recruiter in recruiters | filter: filterFunction" class="col-md-4 text-center" ng-click="showUser(recruiter)">
      <h4>{{recruiter.username}}</h4>
      <h5>{{recruiter.company}}</h5>
      <h5>{{recruiter.position}}</h5>
      <h5>{{recruiter.experience}} years</h5>
      <h5>{{recruiter.email}}</h5>
    </li>
  </ul>

  <!-- Opens user profile on li click -->
  <user-profile></user-profile>

</div>
<div class="panel" ng-show="isSelected(2)">

<!-- Filter Results by Search -->
<search-form></search-form>

  <h3 class="section-titles">Hiring Managers</h3>
  <ul ng-hide="profileShow()">
    <li ng-repeat="manager in managers | filter: filterFunction" class="col-md-4 text-center" ng-click="showUser(manager)">
      <h4>{{manager.username}}</h4>
      <h5>{{manager.company}}</h5>
      <h5>{{manager.position}}</h5>
      <h5>{{manager.experience}} years</h5>
      <h5>{{manager.email}}</h5>
    </li>
  </ul>

  <!-- Opens user profile on li click -->
  <user-profile></user-profile>

</div>
<div class="panel" ng-show="isSelected(3)">

<!-- Filter Results by Search -->
<search-form></search-form>

  <h3 class="section-titles">Job Seekers</h3>
  <ul ng-hide="profileShow()">
  <li ng-repeat="seeker in seekers | filter: filterFunction" class="col-md-4 text-center" ng-click="showUser(seeker)">
    <h4>{{seeker.username}}</h4>
    <h5>{{seeker.company}}</h5>
    <h5>{{seeker.position}}</h5>
    <h5>{{seeker.experience}} years</h5>
    <h5>{{seeker.email}}</h5>
  </li>
</ul>

<!-- Opens user profile on li click -->
<user-profile></user-profile>

</div>
<div class="panel" ng-show="isSelected(4)">

<!-- Current User Profile -->
<profile-page></profile-page>

</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Positions:</strong>
  <%= @user.positions %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @user.experience %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>